/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlthanhvien.UI;

import com.mycompany.qlthanhvien.BLL.BLL_ThietBi;
import com.mycompany.qlthanhvien.BLL.ThietBi;
import javax.swing.JFrame;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class UI_JRF_ChonTB extends javax.swing.JFrame {

    /**
     * Creates new form UI_JRF_ChonTB
     */
    private BLL_ThietBi bLL_ThietBi;
    private DefaultTableModel  model;
    public UI_JRF_ChonTB() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
         bLL_ThietBi =  new BLL_ThietBi();
         loadThietBiTable();
        
    }
    
    
    public void loadThietBiTable () {
        List<ThietBi> thietBis = bLL_ThietBi.loadThietBi();
         model = (DefaultTableModel) jTable_TB.getModel();
         model.setRowCount(0);
         for (int i = 0; i<thietBis.size(); i ++ ) {
            Object[] row = {thietBis.get(i).getMaTB(),thietBis.get(i).getTenTB(), thietBis.get(i).getMoTaTB()};
              model.addRow(row);
            }
    }
    
    public void searchThietBiTable (List<ThietBi> thietBis) {
        
         model = (DefaultTableModel) jTable_TB.getModel();
         model.setRowCount(0);
         for (int i = 0; i<thietBis.size(); i ++ ) {
            Object[] row = {thietBis.get(i).getMaTB(),thietBis.get(i).getTenTB(), thietBis.get(i).getMoTaTB()};
              model.addRow(row);
            }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_timKiemTB = new javax.swing.JTextField();
        jButton_timKiemTB = new javax.swing.JButton();
        jButton_lamMoi_timKiemTB = new javax.swing.JButton();
        jComboBox_timKiemTheoTB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_TB = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Chọn thiết bị");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Tìm kiếm :");

        jTextField_timKiemTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_timKiemTBActionPerformed(evt);
            }
        });

        jButton_timKiemTB.setText("Tìm");
        jButton_timKiemTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timKiemTBActionPerformed(evt);
            }
        });

        jButton_lamMoi_timKiemTB.setText("Làm mới");
        jButton_lamMoi_timKiemTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lamMoi_timKiemTBActionPerformed(evt);
            }
        });

        jComboBox_timKiemTheoTB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MaTB", "TenTB" }));

        jTable_TB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã  thiết bị", "Tên thiết bị", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_TB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_TBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_TB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_timKiemTheoTB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_timKiemTB, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_lamMoi_timKiemTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_timKiemTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_timKiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timKiemTB)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_lamMoi_timKiemTB)
                    .addComponent(jComboBox_timKiemTheoTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_timKiemTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_timKiemTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_timKiemTBActionPerformed

    private void jTable_TBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_TBMouseClicked
         
        
        int index = jTable_TB.getSelectedRow();
        model = (DefaultTableModel) jTable_TB.getModel();
        UI_JPN_ThongTinSD.jTextField_maTB.setText(model.getValueAt(index, 0)+"");
        UI_JPN_ThongTinSD.jTextField_tenTB.setText(model.getValueAt(index, 1)+"");
        this.dispose();
        
    }//GEN-LAST:event_jTable_TBMouseClicked

    private void jButton_timKiemTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timKiemTBActionPerformed
        BLL_ThietBi bllThietBi = new BLL_ThietBi();
  
        searchThietBiTable( bllThietBi.findThietBi(jComboBox_timKiemTheoTB.getSelectedIndex()+1, jTextField_timKiemTB.getText().trim()));
    }//GEN-LAST:event_jButton_timKiemTBActionPerformed

    private void jButton_lamMoi_timKiemTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lamMoi_timKiemTBActionPerformed
       loadThietBiTable();
       jTextField_timKiemTB.setText("");
    }//GEN-LAST:event_jButton_lamMoi_timKiemTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_JRF_ChonTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_JRF_ChonTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_JRF_ChonTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_JRF_ChonTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_JRF_ChonTB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_lamMoi_timKiemTB;
    private javax.swing.JButton jButton_timKiemTB;
    private javax.swing.JComboBox<String> jComboBox_timKiemTheoTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_TB;
    private javax.swing.JTextField jTextField_timKiemTB;
    // End of variables declaration//GEN-END:variables
}
