/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlthanhvien.UI;

import java.awt.FontMetrics;
import javax.swing.plaf.basic.BasicTabbedPaneUI;

/**
 *
 * @author quang
 */
public class UI_JPN_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form ThongKe
     */
    public UI_JPN_ThongKe() {
        initComponents();
        UI_JPN_ThongKeTB jPN_ThongKeTB = new UI_JPN_ThongKeTB();
        UI_JPN_ThongKeTV jPN_ThongKeTV = new UI_JPN_ThongKeTV();
        UI_JPN_ThongKeVP jPN_ThongKeVP = new UI_JPN_ThongKeVP();
        jTabbedPane1.addTab("Thống Kê Thiết Bị", jPN_ThongKeTB);
        jTabbedPane1.addTab("Thống Kê Thành Viên", jPN_ThongKeTV);
        jTabbedPane1.addTab("Thống Kê Vi Phạm", jPN_ThongKeVP);
        jTabbedPane1.setUI(new BasicTabbedPaneUI() {
            @Override
            protected int calculateTabHeight(int tabPlacement, int tabIndex, int fontHeight) {
                return 30;
            }

            @Override
            protected int calculateTabWidth(int tabPlacement, int tabIndex, FontMetrics metrics) {
                return 150;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setMinimumSize(new java.awt.Dimension(1000, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
