/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlthanhvien.UI;

import com.mycompany.qlthanhvien.BLL.BLL_ThietBi;
import com.mycompany.qlthanhvien.BLL.ThietBi;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author quang
 */
public class UI_JPN_ThongKeTB extends javax.swing.JPanel {

    private DefaultCategoryDataset dataset;
    private JFreeChart chart;
    private BLL_ThietBi bll_TB;

    public UI_JPN_ThongKeTB() {
        dataset = new DefaultCategoryDataset();
        bll_TB = new BLL_ThietBi();
        List<ThietBi> listItem = bll_TB.loadThietBi();

        for (ThietBi tb : listItem) {
            int matb = tb.getMaTB();
            int firstDigit = 0;
            // Lặp qua từng chữ số của số nguyên cho đến khi tìm được số đầu tiên
            while (matb != 0) {
                firstDigit = matb % 10;
                matb = matb / 10;
            }
            String label = "";
            switch (firstDigit) {
                case 0 ->
                    label = "Chưa Phân Loại";
                case 1 ->
                    label = "Micro";
                case 2 ->
                    label = "Máy chiếu";
                case 3 ->
                    label = "Máy ảnh";
                case 4 ->
                    label = "Cassette";
                case 5 ->
                    label = "Tivi";
                case 6 ->
                    label = "Quạt Đứng";
            }
            dataset.addValue(firstDigit, "Số Lượng", label);
        }

        chart = ChartFactory.createBarChart(
                "THỐNG KÊ SỐ LƯỢNG THIẾT BỊ",
                "THIẾT BỊ",
                "SỐ LƯỢNG THIẾT BỊ",
                dataset, // Dữ liệu của biểu đồ
                org.jfree.chart.plot.PlotOrientation.VERTICAL, // Hướng của biểu đồ
                true, // Có hiển thị chú thích không
                true, // Có hiển thị công cụ đơn giản không
                true // Có tạo tooltips không
        );
        this.setLayout(null);
        ChartPanel chartThongKeTB = new ChartPanel(chart);
        chartThongKeTB.setBounds(40, 100, 920, 450);


// them vào jpanel

        this.add(chartThongKeTB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(1000, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
